# Generated by Django 3.0.6 on 2023-07-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_auto_20200523_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='en_stock',
            field=models.DecimalField(decimal_places=2, max_digits=4, max_length=25),
        ),
    ]
