# Generated by Django 3.0.6 on 2023-07-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_auto_20230723_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='en_stock',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
