# Generated by Django 3.0.6 on 2023-07-25 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_auto_20230723_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
