# Generated by Django 3.0.6 on 2023-07-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nit',
            field=models.CharField(default=15, max_length=20),
            preserve_default=False,
        ),
    ]
