# Generated by Django 3.0.6 on 2023-07-25 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20230725_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='codigo',
        ),
    ]
