# Generated by Django 3.0.6 on 2023-07-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20230725_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chofer', models.CharField(max_length=120)),
                ('patente_camion', models.CharField(max_length=120)),
                ('patente_semi', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha_salida', models.DateField(auto_now=True)),
                ('fecha_llegada', models.DateField()),
                ('costo_total_trasnlado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Costo de Translado')),
            ],
        ),
    ]
