# Generated by Django 3.0.6 on 2023-07-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_viaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='costo_total_trasnlado',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='Costo de Translado'),
            preserve_default=False,
        ),
    ]
