# Generated by Django 3.0.6 on 2023-07-22 22:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_auto_20200523_1529'),
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='nit',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='nombre_factura',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='razon_cancelacion',
        ),
        migrations.AddField(
            model_name='compra',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='producto.Producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 7, 22)),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.DeleteModel(
            name='DetalleCompra',
        ),
    ]
