# Generated by Django 3.0.6 on 2023-07-23 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_auto_20230722_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 7, 23)),
        ),
    ]
