# Generated by Django 3.0.6 on 2023-07-23 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_auto_20230723_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(default=datetime.timezone),
        ),
    ]
