# Generated by Django 3.0.6 on 2023-07-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_auto_20230723_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
