# Generated by Django 3.0.6 on 2023-07-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0005_auto_20230723_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=4, max_length=25),
        ),
    ]
