# Generated by Django 3.0.6 on 2023-07-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0006_auto_20230723_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
