# Generated by Django 3.0.6 on 2023-07-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0007_auto_20230723_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='viaje',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
