# Generated by Django 3.0.6 on 2023-07-26 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_viaje'),
        ('compra', '0010_auto_20230725_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agenda.Viaje'),
        ),
    ]
