# Generated by Django 3.0.6 on 2023-07-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0011_auto_20230725_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
