# Generated by Django 3.0.6 on 2023-07-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0011_detalleventa_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='nombre_factura',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Vendedor'),
        ),
    ]
