# Generated by Django 3.0.6 on 2023-07-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0014_auto_20230723_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
