# Generated by Django 3.0.6 on 2023-07-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0015_auto_20230723_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=25, null=True),
        ),
    ]
