# Generated by Django 3.0.6 on 2023-07-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0019_auto_20230725_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
